resolver: lts-8.0

packages:
- '.'

extra-deps:
  - typed-process-0.1.0.0
  - yesod-markdown-0.11.3
  - yesod-paginator-0.11.0
  - amazonka-s3-streaming-0.1.0.4
  - load-env-0.1.1
  - directory-1.2.7.1
  - heroku-persistent-0.2.0
  - heroku-0.1.2.3

flags: {}

extra-package-dbs: []
