resolver: lts-8.0

packages:
- '.'

extra-deps:
  - typed-process-0.1.0.0
  - yesod-markdown-0.11.2
  - yesod-paginator-0.10.1
  - amazonka-s3-streaming-0.1.0.4
  - load-env-0.1.1
  - pandoc-1.17.2
  - aeson-0.11.3.0
  - directory-1.2.7.1
  - pandoc-types-1.16.1.1
  - texmath-0.8.6.7

flags: {}

extra-package-dbs: []
