static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4"
port:           "_env:PORT:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"
log-level: "_env:LOG_LEVEL:info"

database:
  user:     "_env:PGUSER:featureless_void"
  password: "_env:PGPASS:featureless_void"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  # See config/test-settings.yml for an override during tests
  database: "_env:PGDATABASE:featureless_void_dev"
  poolsize: "_env:PGPOOLSIZE:10"
